steps:
# Build Docker image: docker build -f Dockerfile -t gcr.io/my-project/my-image:latest .
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile', '-t', 'gcr.io/kubernetes-test-214217/github-uddhav29-simple-rest-app:master', '.']

# Push to GCR: gcloud docker -- push gcr.io/my-project/my-image:latest
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/kubernetes-test-214217/github-uddhav29-simple-rest-app:master']

# Connect to GCE server and pull new image
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://staging.kubernetes-test-214217.appspot.com/Kubernetes test-86404511a8b0.json', '.']  
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud auth activate-service-account --key-file Kubernetes test-86404511a8b0.json
      gcloud app deploy --image-url=gcr.io/kubernetes-test-214217/github-uddhav29-simple-rest-app@sha256:b50538aaf1dc1c70ae28e5f8e245b29fcba69235c11757ec6284c79b85422735