steps:
# Build Docker image: docker build -f Dockerfile -t gcr.io/my-project/my-image:latest .
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile', '-t', 'gcr.io/kubernetes-test-214217/github-uddhav29-simple-rest-app:master', '.']

# Push to GCR: gcloud docker -- push gcr.io/my-project/my-image:latest
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/kubernetes-test-214217/github-uddhav29-simple-rest-app:master']

 # Connect to server and start new container
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'INSTANCE_NAME', '--', 'docker run -d -p 8085:8085 gcr.io/kubernetes-test-214217/github-uddhav29-simple-rest-app:master']

